### ISSUE TITLE
Gitter/Slack

### ISSUE THREAD

**Issue by iamricard** [slorber/scalable-frontend-with-elm-or-redux#23]
Hi all!

I find myself contacting some of you on twitter which like a non-ideal medium to
discuss. Would having a Slack community or Gitter a good idea? I personally feel
like I haven't explored these patterns enough to actually contribute anything
to this repository but I still have questions/things to discuss and I think a chat-like
medium would be a better platform for that.

**Comment by slorber** [comment]
Hi,

I've not much time right now to discuss solutions of this repo (I've not even had time to check all of them or submit my own solution) but maybe others would be interested.

Don't hesitate to set it up if you want :)

**Comment by samsch** [comment]
It seems like it might be non-ideal to create a new location for chatting on this subject, when there is already Reactiflux Discord, as well as #reactjs on freenode (which I can say from personal experience is happy to have this type of discussion, even if it's not strictly React). However, a less transient medium might be good as well.

**Comment by slorber** [comment]
@samsch as this channel won't probably be very active, it's better to have chat persistence. I'm ok for Discord / Reactiflux so just put the channel in the readme once created
