### ISSUE TITLE
Solution feedback : redux-fly

### ISSUE THREAD

**Issue by MrEfrem** [slorber/scalable-frontend-with-elm-or-redux#37]
I send [PR](https://github.com/slorber/scalable-frontend-with-elm-or-redux/pull/36) which contains example rapid creation scalable React + Redux applications with help of [Redux-fly](https://github.com/MrEfrem/redux-fly).

**Comment by slorber** [comment]
Hi and thanks for your contribution

It looks to me your solution is quite close to [redux-lean](https://github.com/epeli/lean-redux) of @epeli and [redux-react-local](https://github.com/threepointone/redux-react-local) of @threepointone . I like this approach as it's probably the most easy to use and is pragmatic, but as far as I'm concerned I think other apis are more easy to understand than yours

**Comment by MrEfrem** [comment]
Hi. Thank for feedback. What it seemed to you difficult? Let's together make to API ease.

**Comment by MrEfrem** [comment]
I sended new [PR](https://github.com/slorber/scalable-frontend-with-elm-or-redux/pull/38). Replace is signature `listenActions` in `createReducer`. Now `listenActions` might 
only is function and must have structure of `reducer`.
I think this behavior is more simple to understand.

**Comment by MrEfrem** [comment]
Why you silent @slorber?

**Comment by slorber** [comment]
@MrEfrem I'm sorry I don't have much time for open source currently

**Comment by MrEfrem** [comment]
Thanks
